CREATE TABLE IF NOT EXISTS `lbtablet_ambulance_conditions_categories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `title` (`title`)
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO `lbtablet_ambulance_conditions_categories` (`id`, `title`) VALUES
	(29, 'Cancer Types'),
	(24, 'Cardiovascular Conditions'),
	(31, 'Endocrine Disorders'),
	(26, 'Gastrointestinal Conditions'),
	(27, 'Infectious Diseases'),
	(28, 'Mental Health Conditions'),
	(32, 'Neurological Conditions'),
	(25, 'Orthopedic Injuries'),
	(30, 'Respiratory Conditions');

CREATE TABLE IF NOT EXISTS `lbtablet_ambulance_conditions` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `severity` varchar(25) NOT NULL,
  `category_id` int(10) unsigned NOT NULL,
  `title` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `severity` (`severity`,`category_id`,`title`),
  KEY `category_id` (`category_id`),
  CONSTRAINT `lbtablet_ambulance_conditions_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `lbtablet_ambulance_conditions_categories` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=172 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO `lbtablet_ambulance_conditions` (`id`, `severity`, `category_id`, `title`) VALUES
	(98, 'critical', 24, 'Aortic Aneurysm'),
	(91, 'critical', 24, 'Heart Attack'),
	(92, 'critical', 24, 'Heart Failure'),
	(94, 'critical', 24, 'Stroke'),
	(103, 'critical', 25, 'Fractured Hip'),
	(108, 'critical', 25, 'Pelvic Fracture'),
	(126, 'critical', 27, 'Ebola Virus Disease'),
	(123, 'critical', 27, 'Meningitis'),
	(145, 'critical', 29, 'Brain Cancer'),
	(138, 'critical', 29, 'Breast Cancer'),
	(142, 'critical', 29, 'Colon Cancer'),
	(141, 'critical', 29, 'Leukemia'),
	(143, 'critical', 29, 'Lymphoma'),
	(144, 'critical', 29, 'Pancreatic Cancer'),
	(139, 'critical', 29, 'Prostate Cancer'),
	(149, 'critical', 30, 'Lung Cancer'),
	(153, 'critical', 30, 'Pulmonary Embolism'),
	(170, 'critical', 32, 'Spinal Cord Injury'),
	(163, 'critical', 32, 'Traumatic Brain Injury'),
	(97, 'minor', 24, 'Angina'),
	(95, 'minor', 24, 'Arrhythmia'),
	(96, 'minor', 24, 'High Blood Pressure'),
	(100, 'minor', 24, 'Peripheral Artery Disease'),
	(101, 'minor', 25, 'Broken Arm'),
	(109, 'minor', 25, 'Rotator Cuff Tear'),
	(106, 'minor', 25, 'Sprained Ankle'),
	(110, 'minor', 25, 'Tennis Elbow'),
	(104, 'minor', 25, 'Torn ACL'),
	(114, 'minor', 26, 'Gastroesophageal Reflux Disease (GERD)'),
	(118, 'minor', 26, 'Peptic Ulcer'),
	(124, 'minor', 27, 'Influenza (Flu)'),
	(127, 'minor', 27, 'Zika Virus'),
	(131, 'minor', 28, 'Anxiety Disorder'),
	(133, 'minor', 28, 'Obsessive-Compulsive Disorder (OCD)'),
	(135, 'minor', 28, 'Phobias'),
	(147, 'minor', 30, 'Asthma'),
	(152, 'minor', 30, 'Bronchitis'),
	(151, 'minor', 30, 'Sleep Apnea'),
	(160, 'minor', 31, 'Hyperthyroidism'),
	(157, 'minor', 31, 'Thyroid Disorders'),
	(169, 'minor', 32, 'Bell’s Palsy'),
	(171, 'minor', 32, 'Cluster Headaches'),
	(162, 'minor', 32, 'Concussion'),
	(168, 'minor', 32, 'Migraine'),
	(93, 'moderate', 24, 'Coronary Artery Disease'),
	(99, 'moderate', 24, 'Deep Vein Thrombosis (DVT)'),
	(102, 'moderate', 25, 'Broken Leg'),
	(105, 'moderate', 25, 'Dislocated Shoulder'),
	(107, 'moderate', 25, 'Herniated Disc'),
	(111, 'moderate', 26, 'Appendicitis'),
	(116, 'moderate', 26, 'Gallstones'),
	(117, 'moderate', 26, 'Pancreatitis'),
	(120, 'moderate', 27, 'COVID-19'),
	(125, 'moderate', 27, 'Malaria'),
	(137, 'moderate', 28, 'Dementia'),
	(129, 'moderate', 28, 'Depression'),
	(132, 'moderate', 28, 'Post-Traumatic Stress Disorder (PTSD)'),
	(146, 'moderate', 30, 'Pneumonia'),
	(159, 'moderate', 31, 'Adrenal Insufficiency (Addison’s Disease)'),
	(158, 'moderate', 31, 'Cushing’s Syndrome'),
	(164, 'moderate', 32, 'Epilepsy'),
	(112, 'severe', 26, 'Crohn\'s Disease'),
	(119, 'severe', 26, 'Hepatitis C'),
	(115, 'severe', 26, 'Irritable Bowel Syndrome (IBS)'),
	(113, 'severe', 26, 'Ulcerative Colitis'),
	(121, 'severe', 27, 'Hepatitis'),
	(122, 'severe', 27, 'HIV/AIDS'),
	(128, 'severe', 27, 'Lyme Disease'),
	(130, 'severe', 28, 'Bipolar Disorder'),
	(136, 'severe', 28, 'Eating Disorders'),
	(134, 'severe', 28, 'Schizophrenia'),
	(140, 'severe', 29, 'Skin Cancer'),
	(148, 'severe', 30, 'Chronic Obstructive Pulmonary Disease (COPD)'),
	(154, 'severe', 30, 'Cystic Fibrosis'),
	(150, 'severe', 30, 'Tuberculosis (TB)'),
	(161, 'severe', 31, 'Polycystic Ovary Syndrome (PCOS)'),
	(155, 'severe', 31, 'Type 1 Diabetes'),
	(156, 'severe', 31, 'Type 2 Diabetes'),
	(167, 'severe', 32, 'Alzheimer’s Disease'),
	(165, 'severe', 32, 'Multiple Sclerosis'),
	(166, 'severe', 32, 'Parkinson\'s Disease');
